import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'dart:convert';
import 'package:speakhands_mobile/l10n/app_localizations.dart';

// A service class that provides the app’s **Terms and Conditions**
// with multilingual support using the app’s localization system.
//
// Instead of loading data from local JSON files, this service now
// retrieves all text content directly from the `AppLocalizations`
// class generated by Flutter’s localization framework.
//
// This approach ensures that translations are consistent across
// the entire app and eliminates the need to maintain separate
// JSON files for each language.
//
// The service dynamically detects the user’s current locale
// (e.g., `en`, `es`, `fr`) and returns a structured Map containing
// all sections of the Terms and Conditions in the appropriate language.
class TermsService {
  // Loads the terms and conditions that match the current app locale.
  //
  // The method first determines the active locale (e.g., "en" or "es")
  // from the BuildContext and uses the corresponding localized strings
  // from `AppLocalizations`.
  //
  // Returns a [Map<String, String>] containing all sections
  // (titles and content) of the terms and conditions.
  static Future<Map<String, String>> loadTerms(BuildContext context) async {
    // Get localized strings
    final loc = AppLocalizations.of(context)!;

    // The structure mirrors the previous JSON layout,
    // but now everything comes from localization (.arb) files.
    return {
      'terms_title': loc.terms_title,
      'terms_section_1_title': loc.terms_section_1_title,
      'terms_section_1_content': loc.terms_section_1_content,
      'terms_section_2_title': loc.terms_section_2_title,
      'terms_section_2_content': loc.terms_section_2_content,
      'terms_section_3_title': loc.terms_section_3_title,
      'terms_section_3_content': loc.terms_section_3_content,
      'terms_section_4_title': loc.terms_section_4_title,
      'terms_section_4_content': loc.terms_section_4_content,
      'terms_section_5_title': loc.terms_section_5_title,
      'terms_section_5_content': loc.terms_section_5_content,
      'terms_section_6_title': loc.terms_section_6_title,
      'terms_section_6_content': loc.terms_section_6_content,
    };
  }
}

